# root/docker-compose.prod.yml
version: '3.8'
services:
  backend:
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  frontend:
    environment:
      NODE_ENV: production
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: ${PROD_DB_PASS}  # From .env file
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G

  redis:
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  kali:
    security_opt:
      - seccomp:./docker/security-policies/seccomp-profile.json
      - apparmor:./docker/security-policies/apparmor-profile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  prometheus:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G

  grafana:
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: grafana-piechart-panel

networks:
  isolated-test:
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"