#!/bin/bash

echo "=================================================="
echo "📚 SecLists Integration - Before & After"
echo "=================================================="
echo ""
echo "❌ OLD APPROACH (Hardcoded Directories):"
echo "   - Test paths: /admin, /api, /config, /.git, /swagger"
echo "   - Total paths tested: ~10-20 hardcoded"
echo "   - Coverage: Basic, might miss many directories"
echo ""
echo "✅ NEW APPROACH (SecLists Wordlists):"
echo ""
echo "📁 Quick Scan Wordlist:"
echo "   - File: Discovery/Web-Content/common.txt"
echo "   - Entries: ~4,700 common paths"
echo "   - Use case: Initial quick reconnaissance"
echo ""
echo "📁 Comprehensive Wordlist:"
echo "   - File: Discovery/Web-Content/directory-list-2.3-medium.txt"
echo "   - Entries: ~220,000 directory names"
echo "   - Use case: Thorough directory enumeration"
echo ""
echo "📁 API Discovery Wordlist:"
echo "   - File: Discovery/Web-Content/api/api-endpoints-mazen160.txt"
echo "   - Entries: Specialized API endpoint patterns"
echo "   - Use case: Finding hidden API endpoints"
echo ""
echo "📊 COMPARISON:"
echo "Old: ~20 paths × 8 subdomains = 160 tests"
echo "New: 4,700+ paths × 8 subdomains = 37,600+ tests (just with common.txt!)"
echo ""
echo "🎯 BENEFITS:"
echo "1. Industry-standard wordlists used by professionals"
echo "2. Comprehensive coverage - won't miss common directories"
echo "3. Context-aware - AI selects appropriate wordlists"
echo "4. Scalable - can adjust based on time/depth needed"
echo ""
echo "🚀 The AI will now automatically:"
echo "- Select appropriate SecLists wordlists"
echo "- Plan individual scans per subdomain"
echo "- Use different wordlists for different contexts"
echo "- Ensure nothing is missed through exhaustive coverage"
echo ""